export interface IndianStateInfo {
  name: string;
  code: string;
  type: 'state' | 'ut';
}

export const ALL_INDIAN_STATES_DATA: IndianStateInfo[] = [
  { name: "Andhra Pradesh", code: "37", type: "state" },
  { name: "Arunachal Pradesh", code: "12", type: "state" },
  { name: "Assam", code: "18", type: "state" },
  { name: "Bihar", code: "10", type: "state" },
  { name: "Chhattisgarh", code: "22", type: "state" },
  { name: "Goa", code: "30", type: "state" },
  { name: "Gujarat", code: "24", type: "state" },
  { name: "Haryana", code: "06", type: "state" },
  { name: "Himachal Pradesh", code: "02", type: "state" },
  { name: "Jharkhand", code: "20", type: "state" },
  { name: "Karnataka", code: "29", type: "state" },
  { name: "Kerala", code: "32", type: "state" },
  { name: "Madhya Pradesh", code: "23", type: "state" },
  { name: "Maharashtra", code: "27", type: "state" },
  { name: "Manipur", code: "14", type: "state" },
  { name: "Meghalaya", code: "17", type: "state" },
  { name: "Mizoram", code: "15", type: "state" },
  { name: "Nagaland", code: "13", type: "state" },
  { name: "Odisha", code: "21", type: "state" },
  { name: "Punjab", code: "03", type: "state" },
  { name: "Rajasthan", code: "08", type: "state" },
  { name: "Sikkim", code: "11", type: "state" },
  { name: "Tamil Nadu", code: "33", type: "state" },
  { name: "Telangana", code: "36", type: "state" },
  { name: "Tripura", code: "16", type: "state" },
  { name: "Uttar Pradesh", code: "09", type: "state" },
  { name: "Uttarakhand", code: "05", type: "state" },
  { name: "West Bengal", code: "19", type: "state" },
  // Union Territories
  { name: "Andaman and Nicobar Islands", code: "35", type: "ut" },
  { name: "Chandigarh", code: "04", type: "ut" },
  { name: "Dadra and Nagar Haveli and Daman and Diu", code: "26", type: "ut" },
  { name: "Delhi", code: "07", type: "ut" },
  { name: "Jammu and Kashmir", code: "01", type: "ut" },
  { name: "Ladakh", code: "38", type: "ut" },
  { name: "Lakshadweep", code: "31", type: "ut" },
  { name: "Puducherry", code: "34", type: "ut" },
];

export const INDIAN_STATES: string[] = [
  "N/A",
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Other"
];

export const INDIAN_STATE_CODE_MAP: Record<string, string> = {
  "Andhra Pradesh": "37",
  "Arunachal Pradesh": "12",
  "Assam": "18",
  "Bihar": "10",
  "Chhattisgarh": "22",
  "Goa": "30",
  "Gujarat": "24",
  "Haryana": "06",
  "Himachal Pradesh": "02",
  "Jharkhand": "20",
  "Karnataka": "29",
  "Kerala": "32",
  "Madhya Pradesh": "23",
  "Maharashtra": "27",
  "Manipur": "14",
  "Meghalaya": "17",
  "Mizoram": "15",
  "Nagaland": "13",
  "Odisha": "21",
  "Orissa": "21",
  "Punjab": "03",
  "Rajasthan": "08",
  "Sikkim": "11",
  "Tamil Nadu": "33",
  "Telangana": "36",
  "Tripura": "16",
  "Uttar Pradesh": "09",
  "Uttarakhand": "05",
  "West Bengal": "19",
  "Andaman and Nicobar Islands": "35",
  "Chandigarh": "04",
  "Dadra and Nagar Haveli and Daman and Diu": "26",
  "Delhi": "07",
  "Jammu and Kashmir": "01",
  "Ladakh": "38",
  "Lakshadweep": "31",
  "Puducherry": "34"
};

export function getStateCodeByName(stateName: string): string {
  if (!stateName) return "";
  const trimmed = stateName.trim();
  return INDIAN_STATE_CODE_MAP[trimmed] || "";
}
